api_platform:
    show_webby: false
    formats:
        json: ['application/json']
        html: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    error_formats:
        jsonproblem: ['application/problem+json']
    enable_re_doc: false
